# 1. Array Creation:
a. Create a 1D NumPy array of numbers from 0 to 9.\
b. Create a 3x3 NumPy array of all zeros.\
c. Create a 4x4 identity matrix.\
d. Create an array of 10 numbers between 0 and 1 (inclusive).\


In [2]:
import numpy as np

a = np.arange(0, 10, 1)
print(a)

b = np.zeros((3, 3))
print("\n", b)

c = np.eye(4)
print("\n", c)

d = np.linspace(0, 1, 10)
print("\n", d)

[0 1 2 3 4 5 6 7 8 9]

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# 2. Array Inspection
a. Create a 2D array and print its shape and data type.\
b. Check how many dimensions it has.\
c. Get the size (total number of elements).


In [3]:
array2D = np.array([[1,2,3],[4,5,6]])
print("Shape:", array2D.shape)
print("Data Type:", type(array2D))
print("Dimensions:", array2D.ndim)
print("Size:", array2D.size)

Shape: (2, 3)
Data Type: <class 'numpy.ndarray'>
Dimensions: 2
Size: 6


# Use the given array to answer the questions below:
`` arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]) ``\
a. Slice the middle element (50).\
b. Get the last column.\
c. Get the first two rows.\
d. Return all the values greater than 50\

In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("Middle Element:", arr[1, 1])

print("Last Column:", arr[-1])

print("1st & 2nd Column:",arr[0], arr[1])

print("Greater than 50:", arr[arr>50])



Middle Element: 50
Last Column: [70 80 90]
1st & 2nd Column: [10 20 30] [40 50 60]
Greater than 50: [60 70 80 90]


# 4. Use the given arrays to answer the questions below:
a = np.array([1, 2, 3])\
b = np.array([4, 5, 6])\
a. Add a and b.\
b. Multiply a and b element-wise.\
c. Calculate the dot product of a and b.\
d. Find the mean and standard deviation of b.


In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

add1 = a+b
print("Addition:",add1)

mult1 = a*b
print("Multiplication:",mult1)

dot1 = np.dot(a, b)
print("Dot Product",dot1)

mean1 = np.mean(b)
std1 = np.std(b)

print("Mean:", mean1)
print("Standard Deviation:", std1)

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot Product 32
Mean: 5.0
Standard Deviation: 0.816496580927726


# 5. Given two numpy arrays A and B, apply the formula given below

In [6]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
z = (A*A)+np.sin(B)
sub = A-B
base = np.abs(sub)
base = np.sqrt(base+1)
z = z / base
print(z)

[0.12159875 1.52053786 4.36029225]


# 6. Run the code given below and explain its output in 2-3 lines.

In [7]:
import numpy as np
arr = np.random.randint(-50, 151, size=100)
arr_reshaped = arr.reshape((10, 10))
arr_reshaped[arr_reshaped < 0] = 0
arr_min = arr_reshaped.min()
arr_max = arr_reshaped.max()
normalized = (arr_reshaped - arr_min) / (arr_max - arr_min)
row_means = normalized.mean(axis=1)
print("Original reshaped array (negatives replaced):\n", arr_reshaped)
print("\nNormalized array:\n", normalized)
print("\nRow-wise means:\n", row_means)


# Explanation:
# the reshaped array has a range of positive values from 0 to 150
# the normalized array has
# The mean of the normalized array rows are calclated resulting in a 10 number array

Original reshaped array (negatives replaced):
 [[ 30 100  47  15   0  25  78  61  34  98]
 [ 80  68 102  59   0  12 103  49 106  64]
 [142  16   0  37   0   0  28  55   0 103]
 [ 81   0  83   0   0  83  76   7  85  43]
 [ 36  37   0 147  75  92  39  97 133   6]
 [ 78  88   0  61 143  24  53   0  59  81]
 [102  89  88   0 102   2 150  55  77  66]
 [ 16 125 137 146 118  37 124  20 104   0]
 [  0 131   0 143  89 120  78   0   7  83]
 [ 25   3  48 139  17  22   7  61   8   0]]

Normalized array:
 [[0.2        0.66666667 0.31333333 0.1        0.         0.16666667
  0.52       0.40666667 0.22666667 0.65333333]
 [0.53333333 0.45333333 0.68       0.39333333 0.         0.08
  0.68666667 0.32666667 0.70666667 0.42666667]
 [0.94666667 0.10666667 0.         0.24666667 0.         0.
  0.18666667 0.36666667 0.         0.68666667]
 [0.54       0.         0.55333333 0.         0.         0.55333333
  0.50666667 0.04666667 0.56666667 0.28666667]
 [0.24       0.24666667 0.         0.98       0.5       

# 7. You have a flattened array of 12 elements:

In [8]:
arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
newArr = arr.reshape(3, 4)
print(newArr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print("Standard Deviation of Row:", np.std(newArr, axis=1))
print("Standard Deviation of Column:", np.std(newArr, axis=0))

Standard Deviation of Row: [1.11803399 1.11803399 1.11803399]
Standard Deviation of Column: [3.26598632 3.26598632 3.26598632 3.26598632]


# 8. Create a Pandas Series from a list: [10, 20, 30, 40, 50].

In [11]:
import pandas as pd

my_series = pd.Series([1, 2, 3, 4, 5])
print(my_series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


# 9. Create a DataFrame with the following data:

In [38]:
s1 = pd.DataFrame({'Name':['Alice', 'Bob', 'Charlie'],
                  'Age': [25, 30, 35],
                  'City':['Lahore', 'Karachi', 'Lahore']})

print(s1.head(1))
print(s1.tail(1))

print("Number of (Rows, Columns):", s1.shape)
print("Data Type of Columns:", s1.dtypes)

selcName = s1.Name
print("Name Column selected:\n",selcName)

selcRow = s1[s1['Name']=='Bob']
print("Name==Bob row selected:\n",selcRow)

selc23 = s1.iloc[1,2]
print("2nd row and 3rd column selected:\n",selc23)

selcAge28 = s1[s1['Age']>28]
print("All rows with Age>28 selected:\n",selcAge28)

s1['Score'] = [85, 90, 95]
print("New Data Set:\n",s1)

s1.loc[s1['Name'] == 'Charlie', 'City'] = 'Multan'
selcRow = s1[s1['Name']=='Charlie']
print("Name==Charlie row selected:\n", selcRow)

s1.drop("Score", axis=1)

avg = s1["Age"].sum() / s1["Age"].count()
print("\nAverage of Age is:", avg)

unq = s1["City"].nunique()
print("Unique Count of City is:", unq)

s1.describe()

    Name  Age    City
0  Alice   25  Lahore
      Name  Age    City
2  Charlie   35  Lahore
Number of (Rows, Columns): (3, 3)
Data Type of Columns: Name    object
Age      int64
City    object
dtype: object
Name Column selected:
 0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
Name==Bob row selected:
   Name  Age     City
1  Bob   30  Karachi
2nd row and 3rd column selected:
 Karachi
All rows with Age>28 selected:
       Name  Age     City
1      Bob   30  Karachi
2  Charlie   35   Lahore
New Data Set:
       Name  Age     City  Score
0    Alice   25   Lahore     85
1      Bob   30  Karachi     90
2  Charlie   35   Lahore     95
Name==Charlie row selected:
       Name  Age    City  Score
2  Charlie   35  Multan     95

Average of Age is: 30.0
Unique Count of City is: 3


Age  Score
count   3.0    3.0
mean   30.0   90.0
std     5.0    5.0
min    25.0   85.0
25%    27.5   87.5
50%    30.0   90.0
75%    32.5   92.5
max    35.0   95.0